from ubuntu:14.04

#Create Workspace
RUN mkdir /usr/sparqlmap
WORKDIR /usr/sparqlmap

#Install Git, Openjdk and maven
RUN sudo apt-get update
RUN sudo apt-get install -y openjdk-7-jdk openjdk-7-source openjdk-7-demo openjdk-7-doc openjdk-7-jre-headless openjdk-7-jre-lib
RUN sudo apt-get install -y maven
RUN sudo apt-get install -y git


# clone SparqlMap-Client
RUN git clone https://github.com/tomatophantastico/sparqlmap.git

# clone and install JSqlParser
# Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.4:compile (default-compile) on project jsqlparser: Compilation failure: Compilation failure:
# [ERROR] bootstrap class path not set in conjunction with -source 1.6

#RUN  cd sparqlmap && git clone https://github.com/tomatophantastico/sparqlmap-jsqlparser.git
#RUN  cd sparqlmap/sparqlmap-jsqlparser &&  mvn package


#RUN cd sparqlmap && git clone https://github.com/tomatophantastico/sparqlmap-core.git
#RUN cd sparqlmap/sparqlmap-core  && git checkout feature/travisCi
#RUN cd sparqlmap/sparqlmap-core/ && ./gradlew -x test publishToMavenLocal

RUN cd sparqlmap && git clone https://github.com/tomatophantastico/metamodel.git
RUN cd sparqlmap/metamodel && mvn install -Dmaven.test.skip=true

RUN cd sparqlmap/ && ./gradlew -x test installDist

CMD /usr/sparqlmap/sparqlmap/build/install/sparqlmap/bin/sparqlmap -dburl $DB_URL -dbuser $DB_USER -dbpassword $DB_PASS
