FROM java:openjdk-7-jdk

WORKDIR /usr

RUN wget https://github.com/tomatophantastico/sparqlmap/releases/download/v0.6.4-SNAPSHOT/sparqlmap.zip
RUN unzip sparqlmap.zip && rm -r sparqlmap.zip

RUN cd sparqlmap 

ADD driver/mysql-connector-java-5.1.37-bin.jar /usr/sparqlmap/lib/mysql-connector-java-5.1.37-bin.jar
ADD db.properties /usr/sparqlmap/bin/

WORKDIR  /usr/sparqlmap/bin/ 
CMD ./sparqlmap -dburi $DB_URL -dbuser $DB_USER -dbpass $DB_PASS -dumb 

